use_frameworks!

platform :ios, '8.0'

target 'XVIEWVideoManager_Example' do
  pod 'XVIEWVideoManager', :path => '../'

  target 'XVIEWVideoManager_Tests' do
    inherit! :search_paths

    
  end
end
